// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8bJnQrg7PmAZgVc1hQYnq9czhc8OTj7s',
    appId: '1:308636382575:web:3b8452c11ef1a77d82249a',
    messagingSenderId: '308636382575',
    projectId: 'e-commerce-e9f06',
    authDomain: 'e-commerce-e9f06.firebaseapp.com',
    storageBucket: 'e-commerce-e9f06.appspot.com',
    measurementId: 'G-2R3PB1MMQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS-TFPznUSEsLCZEnrdKth2NK2hod-x8k',
    appId: '1:308636382575:android:a10732ac0c617e0282249a',
    messagingSenderId: '308636382575',
    projectId: 'e-commerce-e9f06',
    storageBucket: 'e-commerce-e9f06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxi-X86WiQex6ywZzeYRsIUtaFxrXR9SQ',
    appId: '1:308636382575:ios:f7b23b8066e2c6ee82249a',
    messagingSenderId: '308636382575',
    projectId: 'e-commerce-e9f06',
    storageBucket: 'e-commerce-e9f06.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
