// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLpP5sTo4C2P1CuvxchKtN78UhJ3r6InE',
    appId: '1:724239432086:web:265e25b218a55a7f87c5b7',
    messagingSenderId: '724239432086',
    projectId: 'e-commerce-fbb2e',
    authDomain: 'e-commerce-fbb2e.firebaseapp.com',
    storageBucket: 'e-commerce-fbb2e.appspot.com',
    measurementId: 'G-T963KHX3LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7vRpxtqT9A-NuU07Cv7auMTrya13OKeg',
    appId: '1:724239432086:android:6308a10c7703975d87c5b7',
    messagingSenderId: '724239432086',
    projectId: 'e-commerce-fbb2e',
    storageBucket: 'e-commerce-fbb2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBobZv62cjIrZL1-lYGWAVwnNxKZy485j0',
    appId: '1:724239432086:ios:7b7e6f2cf712d12587c5b7',
    messagingSenderId: '724239432086',
    projectId: 'e-commerce-fbb2e',
    storageBucket: 'e-commerce-fbb2e.appspot.com',
    androidClientId: '724239432086-nhkf0uj7jv7sf9le1mg7l8lid3m33gfl.apps.googleusercontent.com',
    iosClientId: '724239432086-cmnljq6u4gn01uu7db94u7ka4emu34cv.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
