name: Build and Release APK

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

        # Set environment variables
      - name: Set environment variables
        run: |
          echo "export KEYPASSWORD=${{ secrets.E_COMMERCE_KEY_PASSWORD }}" >> $GITHUB_ENV
          echo "export STOREPASSWORD=${{ secrets.E_COMMERCE_STORE_PASSWORD }}" >> $GITHUB_ENV

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Install Dependencies
        run: flutter pub get

      - name: Set GPG_TTY environment variable
        run: echo "export GPG_TTY=true" >> $GITHUB_ENV


      - name: Decrypt Keystore File
        env:
          RELEASE_KEYSTORE_PHRASE: ${{ secrets.RELEASE_KEYSTORE_PHRASE }}
          RELEASE_KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        run: |
          echo "$RELEASE_KEYSTORE_FILE" > release.keystore.asc
          echo "$RELEASE_KEYSTORE_PHRASE" > keystore_passphrase.txt
          gpg -d --passphrase-file=keystore_passphrase.txt --batch release.keystore.asc > android/app/e-commerce.keystore

      - name: Build APK
        env:
          KEYPASSWORD: ${{ secrets.E_COMMERCE_KEY_PASSWORD }}
          STOREPASSWORD: ${{ secrets.E_COMMERCE_STORE_PASSWORD }}
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
